### ISSUE TITLE
Migrate CircleCI to GitHub Actions

### ISSUE THREAD

**Issue by ennsharma** [oasislabs/toolstate#23]
**What is the problem that you're trying to solve?**
Move our CI/CD workflows to our accepted best practice. For public repositories, this means using GitHub Actions.

**Describe the solution you'd like**
CircleCI should be removed in favor of GitHub Actions.

**Comment by nhynes** [comment]
yep. let's get the aws creds working first. I have a large-ish refactor that I'd like to do in tandem with gh actions (e.g., including builds of oasis-gateway)

**Comment by nhynes** [comment]
resolved by #24
